import { exampleSearchResultsGroups } from './exampleSearchResultsGroups'

const exampleActiveResultsGroup = {
   "list":[
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_48pjg",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"An overview of which breweries are owned by macros, Japanese conglomerates, and religious orders!",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":105,
            "hide_score":false,
            "name":"t3_bl1xdw",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":236,
            "total_awards_received":0,
            "media_embed":{
               "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/iuRveLsoGLQ?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
               "width":600,
               "scrolling":false,
               "height":338
            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":{
               "type":"youtube.com",
               "oembed":{
                  "provider_url":"https://www.youtube.com/",
                  "version":"1.0",
                  "title":"Who Owns Your Favorite Brewery?",
                  "type":"video",
                  "thumbnail_width":480,
                  "height":338,
                  "width":600,
                  "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/iuRveLsoGLQ?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                  "author_name":"Mad Fermentationist",
                  "provider_name":"YouTube",
                  "thumbnail_url":"https://i.ytimg.com/vi/iuRveLsoGLQ/hqdefault.jpg",
                  "thumbnail_height":360,
                  "author_url":"https://www.youtube.com/channel/UCuoU8fmh-1V5P0ATNq9Z_9w"
               }
            },
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{
               "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/iuRveLsoGLQ?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
               "width":600,
               "scrolling":false,
               "media_domain_url":"https://www.redditmedia.com/mediaembed/bl1xdw",
               "height":338
            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":236,
            "approved_by":null,
            "thumbnail":"https://b.thumbs.redditmedia.com/2UuQK4GPZCXBZqGj7_Ow23BO3QJ897bd58x0dkxZkQQ.jpg",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"rich:video",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "created":1557113455,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"youtu.be",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/-GpIUHH_GCb5kvNdYI_UZz-hZTY04z_TmFgYC7yhi7M.jpg?auto=webp&amp;s=070148d85746b58c67221212240f2cbdf0d030f6",
                        "width":480,
                        "height":360
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/-GpIUHH_GCb5kvNdYI_UZz-hZTY04z_TmFgYC7yhi7M.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c8def659ceb474640c48f9980296d6638f1be3f9",
                           "width":108,
                           "height":81
                        },
                        {
                           "url":"https://external-preview.redd.it/-GpIUHH_GCb5kvNdYI_UZz-hZTY04z_TmFgYC7yhi7M.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=cd60da5627a8c2122a4e41789751ce358252629a",
                           "width":216,
                           "height":162
                        },
                        {
                           "url":"https://external-preview.redd.it/-GpIUHH_GCb5kvNdYI_UZz-hZTY04z_TmFgYC7yhi7M.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=f0fa6fffa94e02e1dce2be6bafbbe8eb04a61e9a",
                           "width":320,
                           "height":240
                        }
                     ],
                     "variants":{

                     },
                     "id":"hdC_aKZJpsOnz3hHma_vY6zIe2X9oTKXJaOJI6gefa4"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bl1xdw",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"oldsock",
            "num_crossposts":0,
            "num_comments":48,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bl1xdw/an_overview_of_which_breweries_are_owned_by/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://youtu.be/iuRveLsoGLQ",
            "subreddit_subscribers":366121,
            "created_utc":1557084655,
            "media":{
               "type":"youtube.com",
               "oembed":{
                  "provider_url":"https://www.youtube.com/",
                  "version":"1.0",
                  "title":"Who Owns Your Favorite Brewery?",
                  "type":"video",
                  "thumbnail_width":480,
                  "height":338,
                  "width":600,
                  "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/iuRveLsoGLQ?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                  "author_name":"Mad Fermentationist",
                  "provider_name":"YouTube",
                  "thumbnail_url":"https://i.ytimg.com/vi/iuRveLsoGLQ/hqdefault.jpg",
                  "thumbnail_height":360,
                  "author_url":"https://www.youtube.com/channel/UCuoU8fmh-1V5P0ATNq9Z_9w"
               }
            },
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_augsb",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"'Problematic' slogan pulled by Moosehead Breweries after complaints | CBC News",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":78,
            "hide_score":false,
            "name":"t3_bl0roy",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":65,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":65,
            "approved_by":null,
            "thumbnail":"https://b.thumbs.redditmedia.com/96Y_X3Xt-x3W2LXdInyHmqRHahNXj0DO8D7VmrNxFWc.jpg",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"link",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "created":1557107699,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"cbc.ca",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/T5ZE3D8OxhK083TlWI3my-Qm9QAf1v6AgSZjtMNnKpg.jpg?auto=webp&amp;s=61d6012ecf0c10fb3a1e2c4739ec33c95fb86d5e",
                        "width":620,
                        "height":349
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/T5ZE3D8OxhK083TlWI3my-Qm9QAf1v6AgSZjtMNnKpg.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=02242be778056549694460e978a3ba8c583a52eb",
                           "width":108,
                           "height":60
                        },
                        {
                           "url":"https://external-preview.redd.it/T5ZE3D8OxhK083TlWI3my-Qm9QAf1v6AgSZjtMNnKpg.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=c2822f706dea4fbe2d3ff3b965fc31bc8866c707",
                           "width":216,
                           "height":121
                        },
                        {
                           "url":"https://external-preview.redd.it/T5ZE3D8OxhK083TlWI3my-Qm9QAf1v6AgSZjtMNnKpg.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=695114506ed8cc3caea7dc91b626cdb4e660a87a",
                           "width":320,
                           "height":180
                        }
                     ],
                     "variants":{

                     },
                     "id":"XuCwfXccGqdI1BhufRxOqq4Hw3fZepUyeKJXWLE6QAE"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bl0roy",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"76before84",
            "num_crossposts":0,
            "num_comments":43,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bl0roy/problematic_slogan_pulled_by_moosehead_breweries/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.cbc.ca/news/canada/prince-edward-island/moosehead-alpine-ad-permission-forgiveness-1.5122032",
            "subreddit_subscribers":366121,
            "created_utc":1557078899,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_7e96a",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Brad Pitt’s adorably wholesome brother, Doug, lives in my hometown and remade the ending of Seven for a local brewery commercial",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":105,
            "hide_score":false,
            "name":"t3_bkp3g6",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":743,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":743,
            "approved_by":null,
            "thumbnail":"https://a.thumbs.redditmedia.com/cgK51An5-GCRVABHILBhEs-Fg-H3roXGILk_uWHpf98.jpg",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"link",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "crosspost_parent_list":[
               {
                  "approved_at_utc":null,
                  "subreddit":"videos",
                  "selftext":"",
                  "author_fullname":"t2_11654r",
                  "saved":false,
                  "mod_reason_title":null,
                  "gilded":0,
                  "clicked":false,
                  "title":"Brad Pitt’s adorably wholesome brother, Doug, lives in my hometown and remade the ending of Seven for a local brewery commercial",
                  "link_flair_richtext":[

                  ],
                  "subreddit_name_prefixed":"r/videos",
                  "hidden":false,
                  "pwls":6,
                  "link_flair_css_class":"cat-advert",
                  "downs":0,
                  "thumbnail_height":105,
                  "hide_score":false,
                  "name":"t3_bkgxle",
                  "quarantine":false,
                  "link_flair_text_color":"light",
                  "author_flair_background_color":null,
                  "subreddit_type":"public",
                  "ups":2015,
                  "total_awards_received":0,
                  "media_embed":{
                     "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/UiyL-AAUnvA?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                     "width":600,
                     "scrolling":false,
                     "height":338
                  },
                  "thumbnail_width":140,
                  "author_flair_template_id":null,
                  "is_original_content":false,
                  "user_reports":[

                  ],
                  "secure_media":{
                     "oembed":{
                        "provider_url":"https://www.youtube.com/",
                        "version":"1.0",
                        "title":"6ix",
                        "thumbnail_width":480,
                        "height":338,
                        "width":600,
                        "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/UiyL-AAUnvA?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                        "author_name":"MothersBrewingCo",
                        "provider_name":"YouTube",
                        "thumbnail_url":"https://i.ytimg.com/vi/UiyL-AAUnvA/hqdefault.jpg",
                        "type":"video",
                        "thumbnail_height":360,
                        "author_url":"https://www.youtube.com/user/MothersBrewingCo"
                     },
                     "type":"youtube.com"
                  },
                  "is_reddit_media_domain":false,
                  "is_meta":false,
                  "category":null,
                  "secure_media_embed":{
                     "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/UiyL-AAUnvA?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                     "width":600,
                     "scrolling":false,
                     "media_domain_url":"https://www.redditmedia.com/mediaembed/bkgxle",
                     "height":338
                  },
                  "link_flair_text":"Ad",
                  "can_mod_post":false,
                  "score":2015,
                  "approved_by":null,
                  "thumbnail":"https://a.thumbs.redditmedia.com/cgK51An5-GCRVABHILBhEs-Fg-H3roXGILk_uWHpf98.jpg",
                  "edited":false,
                  "author_flair_css_class":null,
                  "author_flair_richtext":[

                  ],
                  "gildings":{

                  },
                  "post_hint":"rich:video",
                  "content_categories":null,
                  "is_self":false,
                  "mod_note":null,
                  "created":1556968575,
                  "link_flair_type":"text",
                  "wls":6,
                  "banned_by":null,
                  "author_flair_type":"text",
                  "domain":"youtu.be",
                  "selftext_html":null,
                  "likes":null,
                  "suggested_sort":null,
                  "banned_at_utc":null,
                  "view_count":null,
                  "archived":false,
                  "no_follow":false,
                  "is_crosspostable":false,
                  "pinned":false,
                  "over_18":false,
                  "preview":{
                     "images":[
                        {
                           "source":{
                              "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?auto=webp&amp;s=9e93ecc8e92cd8eb5eef7e46c13336d263c262b8",
                              "width":480,
                              "height":360
                           },
                           "resolutions":[
                              {
                                 "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=5738bacd298534bae8cf1011bff2fed32464c01a",
                                 "width":108,
                                 "height":81
                              },
                              {
                                 "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=7c17b35ab6f76f7a8aa0d437dd1e35511947ba15",
                                 "width":216,
                                 "height":162
                              },
                              {
                                 "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=b0991e26ec9b074719982c57a819767d2e8cb764",
                                 "width":320,
                                 "height":240
                              }
                           ],
                           "variants":{

                           },
                           "id":"YLhTgi0d3kIgTMGzfv9L7UO3Sxz_Rzq_zkZzuSjNw0s"
                        }
                     ],
                     "enabled":false
                  },
                  "all_awardings":[

                  ],
                  "media_only":false,
                  "link_flair_template_id":"311403ec-1842-11e7-b359-0ea1c827c510",
                  "can_gild":false,
                  "spoiler":false,
                  "locked":false,
                  "author_flair_text":null,
                  "visited":false,
                  "num_reports":null,
                  "distinguished":null,
                  "subreddit_id":"t5_2qh1e",
                  "mod_reason_by":null,
                  "removal_reason":null,
                  "link_flair_background_color":"#007373",
                  "id":"bkgxle",
                  "is_robot_indexable":true,
                  "report_reasons":null,
                  "author":"mydadsmorningpaper",
                  "num_crossposts":5,
                  "num_comments":140,
                  "send_replies":false,
                  "whitelist_status":"all_ads",
                  "contest_mode":false,
                  "mod_reports":[

                  ],
                  "author_patreon_flair":false,
                  "author_flair_text_color":null,
                  "permalink":"/r/videos/comments/bkgxle/brad_pitts_adorably_wholesome_brother_doug_lives/",
                  "parent_whitelist_status":"all_ads",
                  "stickied":false,
                  "url":"https://youtu.be/UiyL-AAUnvA",
                  "subreddit_subscribers":20319399,
                  "created_utc":1556939775,
                  "media":{
                     "oembed":{
                        "provider_url":"https://www.youtube.com/",
                        "version":"1.0",
                        "title":"6ix",
                        "thumbnail_width":480,
                        "height":338,
                        "width":600,
                        "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/UiyL-AAUnvA?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                        "author_name":"MothersBrewingCo",
                        "provider_name":"YouTube",
                        "thumbnail_url":"https://i.ytimg.com/vi/UiyL-AAUnvA/hqdefault.jpg",
                        "type":"video",
                        "thumbnail_height":360,
                        "author_url":"https://www.youtube.com/user/MothersBrewingCo"
                     },
                     "type":"youtube.com"
                  },
                  "is_video":false
               }
            ],
            "created":1557028565,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"youtu.be",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?auto=webp&amp;s=9e93ecc8e92cd8eb5eef7e46c13336d263c262b8",
                        "width":480,
                        "height":360
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=5738bacd298534bae8cf1011bff2fed32464c01a",
                           "width":108,
                           "height":81
                        },
                        {
                           "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=7c17b35ab6f76f7a8aa0d437dd1e35511947ba15",
                           "width":216,
                           "height":162
                        },
                        {
                           "url":"https://external-preview.redd.it/gTLzTEdZDF3_2waGcJ3lu_xnxweomVEw4wX9lzmKoZ8.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=b0991e26ec9b074719982c57a819767d2e8cb764",
                           "width":320,
                           "height":240
                        }
                     ],
                     "variants":{

                     },
                     "id":"YLhTgi0d3kIgTMGzfv9L7UO3Sxz_Rzq_zkZzuSjNw0s"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bkp3g6",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"monotoonz",
            "num_crossposts":0,
            "num_comments":29,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "crosspost_parent":"t3_bkgxle",
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bkp3g6/brad_pitts_adorably_wholesome_brother_doug_lives/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://youtu.be/UiyL-AAUnvA",
            "subreddit_subscribers":366121,
            "created_utc":1556999765,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"According to Twitter, the 11,500 people who arrived to attend either cannot get in and / or are being required to go inside the stadium (the beer is outside) due to bad weather. \n\nAccording to attendees, the vendors were not set up by 3:00 as promised, they have run out of cups, there are not enough ticket takers to get everyone in the building, and people are demanding a refund. \n\nView Untappd's Twitter account for further information.",
            "author_fullname":"t2_1780m3",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Untappd first ever beer festival is the FyreFest of craft beer",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":null,
            "hide_score":false,
            "name":"t3_bkq9kj",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":116,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":null,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":116,
            "approved_by":null,
            "thumbnail":"self",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "content_categories":null,
            "is_self":true,
            "mod_note":null,
            "created":1557035443,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"self.beer",
            "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;According to Twitter, the 11,500 people who arrived to attend either cannot get in and / or are being required to go inside the stadium (the beer is outside) due to bad weather. &lt;/p&gt;\n\n&lt;p&gt;According to attendees, the vendors were not set up by 3:00 as promised, they have run out of cups, there are not enough ticket takers to get everyone in the building, and people are demanding a refund. &lt;/p&gt;\n\n&lt;p&gt;View Untappd&amp;#39;s Twitter account for further information.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bkq9kj",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"mesmee",
            "num_crossposts":0,
            "num_comments":31,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bkq9kj/untappd_first_ever_beer_festival_is_the_fyrefest/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.reddit.com/r/beer/comments/bkq9kj/untappd_first_ever_beer_festival_is_the_fyrefest/",
            "subreddit_subscribers":366121,
            "created_utc":1557006643,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"Some breweries have extensive programs to test quality for their beer, some have minimal testing (if any). Have you considered it before? Opinions? I'm mostly curious because I have someone in the field and they are being \"let go\" because they are pointing out flaws in that brewery's system (or lack there of).",
            "author_fullname":"t2_7anav",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"How do you feel about breweries with no microprogram?",
            "link_flair_richtext":[
               {
                  "e":"text",
                  "t":"¿Question?"
               }
            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":"",
            "downs":0,
            "thumbnail_height":null,
            "hide_score":false,
            "name":"t3_bl463c",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":0,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":null,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":"¿Question?",
            "can_mod_post":false,
            "score":0,
            "approved_by":null,
            "thumbnail":"self",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "content_categories":null,
            "is_self":true,
            "mod_note":null,
            "created":1557125248,
            "link_flair_type":"richtext",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"self.beer",
            "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Some breweries have extensive programs to test quality for their beer, some have minimal testing (if any). Have you considered it before? Opinions? I&amp;#39;m mostly curious because I have someone in the field and they are being &amp;quot;let go&amp;quot; because they are pointing out flaws in that brewery&amp;#39;s system (or lack there of).&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":true,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "all_awardings":[

            ],
            "media_only":false,
            "link_flair_template_id":"af8f26fe-8996-11e3-9142-22000ab83216",
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bl463c",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"mackbenn",
            "num_crossposts":0,
            "num_comments":4,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bl463c/how_do_you_feel_about_breweries_with_no/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.reddit.com/r/beer/comments/bl463c/how_do_you_feel_about_breweries_with_no/",
            "subreddit_subscribers":366121,
            "created_utc":1557096448,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"I liked those a lot but they're gone now. Anything really similar? I liked how it was dark and rich",
            "author_fullname":"t2_9pv3a",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Anything close to Harpoon Dunkin Coffee Porter?",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":null,
            "hide_score":false,
            "name":"t3_bl3nc5",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":0,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":null,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":0,
            "approved_by":null,
            "thumbnail":"self",
            "edited":1557094536,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "content_categories":null,
            "is_self":true,
            "mod_note":null,
            "created":1557122391,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"self.beer",
            "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I liked those a lot but they&amp;#39;re gone now. Anything really similar? I liked how it was dark and rich&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":true,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bl3nc5",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"jimmpony",
            "num_crossposts":0,
            "num_comments":9,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bl3nc5/anything_close_to_harpoon_dunkin_coffee_porter/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.reddit.com/r/beer/comments/bl3nc5/anything_close_to_harpoon_dunkin_coffee_porter/",
            "subreddit_subscribers":366121,
            "created_utc":1557093591,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_4x3zj",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Was Untappd the Fyre Festival of Charlotte—or simply a rain-delayed beer event? - CharlotteFive",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":93,
            "hide_score":false,
            "name":"t3_bkyok2",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":"",
            "subreddit_type":"public",
            "ups":3,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":3,
            "approved_by":null,
            "thumbnail":"https://b.thumbs.redditmedia.com/SzvAqfXpaYA1AsFVrIOClVJGGISL-fBGeWKM4ShyjAU.jpg",
            "edited":false,
            "author_flair_css_class":"growler",
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"link",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "created":1557097231,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"charlottefive.com",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?auto=webp&amp;s=16b730117fa9b1de7e5ae0d398ee66cbf6427166",
                        "width":1300,
                        "height":867
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=96e6f352a47cf8c59aaef9f1a8152f65c02b25ad",
                           "width":108,
                           "height":72
                        },
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=6f37d9e6d96b3c94bb24f3f4b39de456ebbd566b",
                           "width":216,
                           "height":144
                        },
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=a94ea3307246e96c735709dcee048edafeb1e1a1",
                           "width":320,
                           "height":213
                        },
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=4eb266967f0ebc30d780dabf82b40d34b047c37b",
                           "width":640,
                           "height":426
                        },
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=a4bc8e025bd2a18bbd4453a06a61f0ab3b2ebc8c",
                           "width":960,
                           "height":640
                        },
                        {
                           "url":"https://external-preview.redd.it/Rt5qHbgEXzWxHwxPzccGhPZvTdN1_KAwcoEsksv0vUE.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=ee6cb0d5b935dcdc4df29e74d3d939e4b5607b81",
                           "width":1080,
                           "height":720
                        }
                     ],
                     "variants":{

                     },
                     "id":"nzSiMAjZRWytxdiuQfSQZv2qeooZJjFcG6vqINcMAyo"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":"",
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bkyok2",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"316nuts",
            "num_crossposts":0,
            "num_comments":1,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":"dark",
            "permalink":"/r/beer/comments/bkyok2/was_untappd_the_fyre_festival_of_charlotteor/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.charlottefive.com/untappd-fyre-festival-of-beer-fests/",
            "subreddit_subscribers":366121,
            "created_utc":1557068431,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_a1tto",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Anyone live near Alpharetta, GA? I need to try this and apparently I can't get it anywhere near where I live.",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":140,
            "hide_score":false,
            "name":"t3_bl2m4c",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":1,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":1,
            "approved_by":null,
            "thumbnail":"https://b.thumbs.redditmedia.com/P_8nCXz2Lx-eE9suTDkawnCXIhTdgUIAeBk4iKviV0I.jpg",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"link",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "created":1557116939,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"jekyllbrewing.com",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":true,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/z5q_GWIvZJCKTzmcvH1Myi6CipbZ2281E7UziMwBZBM.jpg?auto=webp&amp;s=f12799e65e640346e79380ea993417f1343b5ace",
                        "width":280,
                        "height":468
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/z5q_GWIvZJCKTzmcvH1Myi6CipbZ2281E7UziMwBZBM.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=ab1c48da2022d14dd02990b0000340c3ed0132d3",
                           "width":108,
                           "height":180
                        },
                        {
                           "url":"https://external-preview.redd.it/z5q_GWIvZJCKTzmcvH1Myi6CipbZ2281E7UziMwBZBM.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=c9557663a422cc428c89fcf54a71738d9ede2882",
                           "width":216,
                           "height":361
                        }
                     ],
                     "variants":{

                     },
                     "id":"ginCKdPgfYYqmJxbiRtguih8fXI4X3L1NGQwmNSbBgE"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bl2m4c",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"LostCauseSPM",
            "num_crossposts":0,
            "num_comments":7,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bl2m4c/anyone_live_near_alpharetta_ga_i_need_to_try_this/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"http://jekyllbrewing.com/beer/pineapple-habanero-hop-dang-diggity/",
            "subreddit_subscribers":366121,
            "created_utc":1557088139,
            "media":null,
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"",
            "author_fullname":"t2_1486k1",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"Made a pilot for a beer travel show, Beer Trippin. Cheers!",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":105,
            "hide_score":false,
            "name":"t3_bkoai4",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":17,
            "total_awards_received":0,
            "media_embed":{
               "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/c5Si3p9P80U?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
               "width":600,
               "scrolling":false,
               "height":338
            },
            "thumbnail_width":140,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":{
               "type":"youtube.com",
               "oembed":{
                  "provider_url":"https://www.youtube.com/",
                  "title":"Beer Trippin | Pilot Episode - Fresno, CA",
                  "type":"video",
                  "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/c5Si3p9P80U?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                  "author_name":"Beer Trippin",
                  "height":338,
                  "width":600,
                  "version":"1.0",
                  "thumbnail_width":480,
                  "thumbnail_height":360,
                  "thumbnail_url":"https://i.ytimg.com/vi/c5Si3p9P80U/hqdefault.jpg",
                  "provider_name":"YouTube",
                  "author_url":"https://www.youtube.com/channel/UCnfH-MVXy0cXLAUaKtUkc-Q"
               }
            },
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{
               "content":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/c5Si3p9P80U?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
               "width":600,
               "scrolling":false,
               "media_domain_url":"https://www.redditmedia.com/mediaembed/bkoai4",
               "height":338
            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":17,
            "approved_by":null,
            "thumbnail":"https://b.thumbs.redditmedia.com/K86ryuhbzOIxKNtW2LSvdN6oxgfacOHY4ad0TxyaTlI.jpg",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "post_hint":"rich:video",
            "content_categories":null,
            "is_self":false,
            "mod_note":null,
            "created":1557024098,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"youtu.be",
            "selftext_html":null,
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":false,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "preview":{
               "images":[
                  {
                     "source":{
                        "url":"https://external-preview.redd.it/in9y1IDxEPI3q-r72yYzpK74T6iQz6bYVxmTz4-lhqY.jpg?auto=webp&amp;s=b72f1f7bd8b396ed4c62c807df3653617355a53d",
                        "width":480,
                        "height":360
                     },
                     "resolutions":[
                        {
                           "url":"https://external-preview.redd.it/in9y1IDxEPI3q-r72yYzpK74T6iQz6bYVxmTz4-lhqY.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=33c9cfeb86b05610ea4d22d544ab554cf0cc0d58",
                           "width":108,
                           "height":81
                        },
                        {
                           "url":"https://external-preview.redd.it/in9y1IDxEPI3q-r72yYzpK74T6iQz6bYVxmTz4-lhqY.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=3757b1692e11dd840e99a4a11b4712f17ac7135a",
                           "width":216,
                           "height":162
                        },
                        {
                           "url":"https://external-preview.redd.it/in9y1IDxEPI3q-r72yYzpK74T6iQz6bYVxmTz4-lhqY.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=93a78875fb5b6b9ed027406502f97f4e42207d11",
                           "width":320,
                           "height":240
                        }
                     ],
                     "variants":{

                     },
                     "id":"fSDQGQbtX1ZoF2p_wom1gx4wbWzCrqsHjcsMLxAkLzA"
                  }
               ],
               "enabled":false
            },
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bkoai4",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"grumpywonka",
            "num_crossposts":0,
            "num_comments":8,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bkoai4/made_a_pilot_for_a_beer_travel_show_beer_trippin/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://youtu.be/c5Si3p9P80U",
            "subreddit_subscribers":366121,
            "created_utc":1556995298,
            "media":{
               "type":"youtube.com",
               "oembed":{
                  "provider_url":"https://www.youtube.com/",
                  "title":"Beer Trippin | Pilot Episode - Fresno, CA",
                  "type":"video",
                  "html":"&lt;iframe width=\"600\" height=\"338\" src=\"https://www.youtube.com/embed/c5Si3p9P80U?feature=oembed&amp;enablejsapi=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen&gt;&lt;/iframe&gt;",
                  "author_name":"Beer Trippin",
                  "height":338,
                  "width":600,
                  "version":"1.0",
                  "thumbnail_width":480,
                  "thumbnail_height":360,
                  "thumbnail_url":"https://i.ytimg.com/vi/c5Si3p9P80U/hqdefault.jpg",
                  "provider_name":"YouTube",
                  "author_url":"https://www.youtube.com/channel/UCnfH-MVXy0cXLAUaKtUkc-Q"
               }
            },
            "is_video":false
         }
      },
      {
         "kind":"t3",
         "data":{
            "approved_at_utc":null,
            "subreddit":"beer",
            "selftext":"I was lucky enough to be offered to keep the leftover beer, in a keg of Stella Artois. The catch is that I have to have the keg itself back to the store on Monday(its Saturday night). Is there anyway possible that I can take all of the beer from the keg, put it into another container and keep it for personal consumption until I finish it?? I'm throwing a party to finish as much as possible but it's damn near full and I KNOW my friends and I can't finish it in 1 night. But I really don't want to waste this much of my favorite beer. I want to return the keg empty on monday with a fridge stocked with beer(somehow) if that makes sense. \n\nPLEASE HELP",
            "author_fullname":"t2_35vx2ole",
            "saved":false,
            "mod_reason_title":null,
            "gilded":0,
            "clicked":false,
            "title":"(PLEASE HELP ME) How to store beer from a keg OUTSIDE of the keg",
            "link_flair_richtext":[

            ],
            "subreddit_name_prefixed":"r/beer",
            "hidden":false,
            "pwls":6,
            "link_flair_css_class":null,
            "downs":0,
            "thumbnail_height":null,
            "hide_score":false,
            "name":"t3_bktc0o",
            "quarantine":false,
            "link_flair_text_color":"dark",
            "author_flair_background_color":null,
            "subreddit_type":"public",
            "ups":3,
            "total_awards_received":0,
            "media_embed":{

            },
            "thumbnail_width":null,
            "author_flair_template_id":null,
            "is_original_content":false,
            "user_reports":[

            ],
            "secure_media":null,
            "is_reddit_media_domain":false,
            "is_meta":false,
            "category":null,
            "secure_media_embed":{

            },
            "link_flair_text":null,
            "can_mod_post":false,
            "score":3,
            "approved_by":null,
            "thumbnail":"self",
            "edited":false,
            "author_flair_css_class":null,
            "author_flair_richtext":[

            ],
            "gildings":{

            },
            "content_categories":null,
            "is_self":true,
            "mod_note":null,
            "created":1557055799,
            "link_flair_type":"text",
            "wls":6,
            "banned_by":null,
            "author_flair_type":"text",
            "domain":"self.beer",
            "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I was lucky enough to be offered to keep the leftover beer, in a keg of Stella Artois. The catch is that I have to have the keg itself back to the store on Monday(its Saturday night). Is there anyway possible that I can take all of the beer from the keg, put it into another container and keep it for personal consumption until I finish it?? I&amp;#39;m throwing a party to finish as much as possible but it&amp;#39;s damn near full and I KNOW my friends and I can&amp;#39;t finish it in 1 night. But I really don&amp;#39;t want to waste this much of my favorite beer. I want to return the keg empty on monday with a fridge stocked with beer(somehow) if that makes sense. &lt;/p&gt;\n\n&lt;p&gt;PLEASE HELP&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "likes":null,
            "suggested_sort":null,
            "banned_at_utc":null,
            "view_count":null,
            "archived":false,
            "no_follow":true,
            "is_crosspostable":false,
            "pinned":false,
            "over_18":false,
            "all_awardings":[

            ],
            "media_only":false,
            "can_gild":false,
            "spoiler":false,
            "locked":false,
            "author_flair_text":null,
            "visited":false,
            "num_reports":null,
            "distinguished":null,
            "subreddit_id":"t5_2qhg1",
            "mod_reason_by":null,
            "removal_reason":null,
            "link_flair_background_color":"",
            "id":"bktc0o",
            "is_robot_indexable":true,
            "report_reasons":null,
            "author":"mixtapematt",
            "num_crossposts":0,
            "num_comments":7,
            "send_replies":true,
            "whitelist_status":"all_ads",
            "contest_mode":false,
            "mod_reports":[

            ],
            "author_patreon_flair":false,
            "author_flair_text_color":null,
            "permalink":"/r/beer/comments/bktc0o/please_help_me_how_to_store_beer_from_a_keg/",
            "parent_whitelist_status":"all_ads",
            "stickied":false,
            "url":"https://www.reddit.com/r/beer/comments/bktc0o/please_help_me_how_to_store_beer_from_a_keg/",
            "subreddit_subscribers":366121,
            "created_utc":1557026999,
            "media":null,
            "is_video":false
         }
      }
   ],
   "entry":0
}


const examplePaginationPayload = {
  groups: exampleSearchResultsGroups,
  activeResultsPageIndex: 1,
  activeResultsGroup: exampleActiveResultsGroup
}

export { examplePaginationPayload }