const exampleSearchResult = {
   "approved_at_utc":null,
   "subreddit":"space",
   "selftext":"Please sort comments by 'new' to find questions that would otherwise be buried.\n\nIn this thread you can ask any space related question that you may have.\n\nTwo examples of potential questions could be; \"How do rockets work?\", or \"How do the phases of the Moon work?\"\n\nIf you see a space related question posted in another subeddit or in this subreddit, then please politely link them to this thread.\n\nAsk away!",
   "author_fullname":"t2_6l4z3",
   "saved":false,
   "mod_reason_title":null,
   "gilded":0,
   "clicked":false,
   "title":"Week of May 05, 2019 'All Space Questions' thread",
   "link_flair_richtext":[

   ],
   "subreddit_name_prefixed":"r/space",
   "hidden":false,
   "pwls":6,
   "link_flair_css_class":"black",
   "downs":0,
   "thumbnail_height":null,
   "hide_score":false,
   "name":"t3_bl05ql",
   "quarantine":false,
   "link_flair_text_color":"dark",
   "author_flair_background_color":null,
   "subreddit_type":"public",
   "ups":9,
   "total_awards_received":0,
   "media_embed":{

   },
   "thumbnail_width":null,
   "author_flair_template_id":null,
   "is_original_content":false,
   "user_reports":[

   ],
   "secure_media":null,
   "is_reddit_media_domain":false,
   "is_meta":false,
   "category":null,
   "secure_media_embed":{

   },
   "link_flair_text":"Discussion",
   "can_mod_post":false,
   "score":9,
   "approved_by":null,
   "thumbnail":"https://b.thumbs.redditmedia.com/Y8yt5FL9p-apoUFTR13lun7ubZ-SKrB2hsX8UB3gICc.jpg",
   "edited":false,
   "author_flair_css_class":null,
   "author_flair_richtext":[

   ],
   "gildings":{

   },
   "content_categories":null,
   "is_self":true,
   "mod_note":null,
   "created":1557104665,
   "link_flair_type":"text",
   "wls":6,
   "banned_by":null,
   "author_flair_type":"text",
   "domain":"self.space",
   "selftext_html":"&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Please sort comments by &amp;#39;new&amp;#39; to find questions that would otherwise be buried.&lt;/p&gt;\n\n&lt;p&gt;In this thread you can ask any space related question that you may have.&lt;/p&gt;\n\n&lt;p&gt;Two examples of potential questions could be; &amp;quot;How do rockets work?&amp;quot;, or &amp;quot;How do the phases of the Moon work?&amp;quot;&lt;/p&gt;\n\n&lt;p&gt;If you see a space related question posted in another subeddit or in this subreddit, then please politely link them to this thread.&lt;/p&gt;\n\n&lt;p&gt;Ask away!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
   "likes":null,
   "suggested_sort":"new",
   "banned_at_utc":null,
   "view_count":null,
   "archived":false,
   "no_follow":true,
   "is_crosspostable":false,
   "pinned":false,
   "over_18":false,
   "all_awardings":[

   ],
   "media_only":false,
   "can_gild":false,
   "spoiler":false,
   "locked":false,
   "author_flair_text":null,
   "visited":false,
   "num_reports":null,
   "distinguished":null,
   "subreddit_id":"t5_2qh87",
   "mod_reason_by":null,
   "removal_reason":null,
   "link_flair_background_color":"",
   "id":"bl05ql",
   "is_robot_indexable":true,
   "report_reasons":null,
   "author":"AutoModerator",
   "num_crossposts":0,
   "num_comments":7,
   "send_replies":false,
   "whitelist_status":"all_ads",
   "contest_mode":false,
   "mod_reports":[

   ],
   "author_patreon_flair":false,
   "author_flair_text_color":null,
   "permalink":"/r/space/comments/bl05ql/week_of_may_05_2019_all_space_questions_thread/",
   "parent_whitelist_status":"all_ads",
   "stickied":true,
   "url":"https://www.reddit.com/r/space/comments/bl05ql/week_of_may_05_2019_all_space_questions_thread/",
   "subreddit_subscribers":15294833,
   "created_utc":1557075865,
   "media":null,
   "is_video":false
}


export { exampleSearchResult };
